### ISSUE TITLE
Allow updatedAt to be set on insert

### ISSUE THREAD

**Issue by jimmiebtlr** [zimme/meteor-collection-timestampable#16]
Or add a way to override this behaviour.

**Comment by zimme** [comment]
Do you have a compelling scenario for why this is needed? I don't have a problem adding this in one way or the other. I just want to see why there's a need for it.

**Comment by jimmiebtlr** [comment]
I'm syncing some record's with another database, and would like to be able to insert a record that has it, yet still have it set correctly for records originating internally.

**Comment by zimme** [comment]
Ok, so I'm thinking that inserts/updates initiated from trusted code (server-side) will respect `createdAt`/`createdBy`/`updatedAt`/`updatedBy` which are provided in the doc when doing the insert/update.

The question is; do we have an option to enable this or do we make this the default, I need to think about that for a while.

The only way I'm seeing this getting into the package quickly is via a PR, otherwise I'll probably not get to it until I'm doing the es2015 rewrite. I'm working on the rewrite for `zimme:collection-behaviours` now and this packge till be the first behaviour which will get the rewrite after the core is rewritten.

**Comment by zimme** [comment]
So I just realized that as a temporary solution you can just use the `collection.direct` from `matb33:collection-hooks` package as that's the package used for the date insertion within the behaviour.

https://github.com/matb33/meteor-collection-hooks#direct-access-circumventing-hooks

**Comment by roelvan** [comment]
@zimme thanks, that'll do for now :+1:

**Comment by jimmiebtlr** [comment]
Works for me as well, thanks.
